# Generated by Django 3.2.12 on 2022-04-10 06:44

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruimentAds',
            fields=[
                ('token', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=2048, null=True)),
                ('thumbnail', models.CharField(max_length=2048, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('province', models.CharField(max_length=64, null=True)),
                ('neighbourhood', models.CharField(max_length=64, null=True)),
                ('education', models.CharField(max_length=64, null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('cooperation', models.CharField(max_length=64, null=True)),
                ('salary', models.BigIntegerField(null=True)),
                ('insurnace', models.CharField(max_length=15, null=True)),
                ('category', models.CharField(max_length=64, null=True)),
                ('sub_category', models.CharField(max_length=64, null=True)),
                ('experience', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=4096, null=True)),
            ],
            options={
                'db_table': 'recruiment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('alt', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='source_logo')),
                ('fa_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('deleted', models.BooleanField(default=False)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.province')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('filter', django.contrib.postgres.fields.jsonb.JSONField()),
                ('raw_filter', django.contrib.postgres.fields.jsonb.JSONField()),
                ('type', models.CharField(choices=[('recruiment', 'recruiment')], max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField()),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_activesearchhistory_related', related_query_name='api_activesearchhistorys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('filter', django.contrib.postgres.fields.jsonb.JSONField()),
                ('raw_filter', django.contrib.postgres.fields.jsonb.JSONField()),
                ('type', models.CharField(choices=[('recruiment', 'recruiment')], max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField()),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_activesearch_related', related_query_name='api_activesearchs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationsToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4096)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_device', to='api.devicetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device')},
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('recruiment', 'recruiment')], max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'type', 'token')},
            },
        ),
    ]
