# Generated by Django 2.2.4 on 2020-11-13 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='tmp_code_sent_counter_in_last_24_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SMSBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_black_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
