# Generated by Django 2.2.4 on 2021-08-01 18:20

import authentication.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201113_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='tmp_code_expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='tmp_code_sent_time',
            field=models.DateTimeField(default=authentication.utils.five_minute_ago),
        ),
    ]
